# Base configs
baseurl: "https://photography.mig21dc.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Shawn Xu"
subtitle: "Sunset Rollercoaster"
author: "Shawn Xu"
header:
 title: "Photography"
 subtitle: "by Shawn Xu"
footer:
 name: "Hey there, my name is Shawn"
 bio: "I am a developer and a tech aficionado from Toronto, ON, Canada. Learning photography."
web_design: "XX"
social_urls:
  instagram: "https://www.instagram.com/mig21dc"
  linkedin: "https://www.linkedin.com/in/shawn-xu-a4997398/"
  github: "https://github.com/MiG-21DC"

theme: jekyll-theme-cayman